[package]
name = "getopt"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
libc = { workspace = true }
utils = { path = "../utils" }